.TH "Chiffres" 3 "Chiffres" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Chiffres
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBChiffres\fP (double initial=0\&.0)"
.br
.ti -1c
.RI "void \fBspend\fP (double amount)"
.br
.ti -1c
.RI "void \fBreceive\fP (double amount)"
.br
.ti -1c
.RI "double \fBmutate\fP (const \fBEthicsScore\fP &ethics, const \fBCyclePhase\fP &cycle)"
.br
.ti -1c
.RI "void \fBset_state\fP (const State s) noexcept"
.br
.ti -1c
.RI "State \fBstate\fP () const noexcept"
.br
.ti -1c
.RI "double \fBtotal\fP () const noexcept"
.br
.ti -1c
.RI "const \fBMemory\fP & \fBmemory\fP () const noexcept"
.br
.ti -1c
.RI "void \fBrecord_flow\fP (double amount, bool incoming)"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Chiffres from the source code\&.
