.TH "Chiffre::EthicsScore" 3 "Chiffres" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Chiffre::EthicsScore \- Ethical score associated with an actor or portfolio\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fR#include <Chiffres\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "double \fBscore\fP = 0\&.0"
.br
.RI "< Range expected in [-1\&.0, +1\&.0]\&. "
.in -1c
.SH "Detailed Description"
.PP 
Ethical score associated with an actor or portfolio\&. 

This influences volatility and drift during mutation:
.IP "\(bu" 2
Positive values (towards +1) reduce variance and add slight positive drift\&.
.IP "\(bu" 2
Negative values (towards -1) increase variance and bias towards losses\&. 
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for Chiffres from the source code\&.
