.TH "Ether" 3 "Chiffres" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Ether
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "double \fBdensity\fP () const noexcept"
.br
.ti -1c
.RI "void \fBconsume\fP (double amount) noexcept"
.br
.ti -1c
.RI "void \fBdissolve\fP (double amount) noexcept"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static \fBEther\fP & \fBinstance\fP ()"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Chiffres from the source code\&.
