.TH "Memory" 3 "Chiffres" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Memory
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "double \fBvolatility_bias\fP = 1\&.0"
.br
.ti -1c
.RI "double \fBstability_bias\fP = 1\&.0"
.br
.ti -1c
.RI "std::uint64_t \fBevents\fP = 0"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Chiffres from the source code\&.
